version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: image_moderation_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: image_moderation_db
    networks:
      - app_network

  api:
    build: .
    container_name: image_moderation_api
    restart: unless-stopped
    ports:
      - "7000:7000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - JWT_SECRET=${JWT_SECRET:-miharbi}
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-admin123}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:
    driver: local

networks:
  app_network:
    driver: bridge
